#!/bin/sh
########################################################################
#
# 2013-02-04
# Gabriel Bretschner
# info@kanedo.net
#
########################################################################
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################
#
# Uberspace Service-Script to start gitlab with daemontools
#
########################################################################
export GITLAB_PORT=54321
export GITLAB_PATH=$HOME/gitlab

cd $GITLAB_PATH
exec bundle exec unicorn_rails -E production -p $GITLAB_PORT 